package com.jacc.everis.productorest.model;
// Generated 7/10/2019 10:56:26 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "productoventa")
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private String nombre;
	private String descripcion;
	private String imagen;
	private double precio;
	private int stock;
//	private Set<Almacen> almacens = new HashSet<Almacen>(0);

	public Producto() {
	}

	public Producto(String nombre, String descripcion, String imagen, double precio, int stock) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.precio = precio;
		this.stock = stock;
	}

//	public Producto(String nombre, String descripcion, String imagen, double precio, int stock, Set<Almacen> almacens) {
//		this.nombre = nombre;
//		this.descripcion = descripcion;
//		this.imagen = imagen;
//		this.precio = precio;
//		this.stock = stock;
//		this.almacens = almacens;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproducto", unique = true, nullable = false)
	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen", nullable = false, length = 200)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
//	public Set<Almacen> getAlmacens() {
//		return this.almacens;
//	}
//
//	public void setAlmacens(Set<Almacen> almacens) {
//		this.almacens = almacens;
//	}

}
